# This workflow validates the Node 24 toolchain on GitHub-hosted runners.
name: Run Node 24 Checks

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      PUBLIC_URL: https://doesitarm.com
      PUBLIC_API_DOMAIN: https://api.doesitarm.com

    strategy:
      matrix:
        node-version: [24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v6
    - name: Setup PNPM
      uses: pnpm/action-setup@v4
      with:
        version: 10.12.1
        run_install: false
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
        cache: pnpm
    - run: pnpm install --frozen-lockfile
    - run: pnpm build
    - run: pnpm test
